{
  imports = [
    ./bat.nix
    ./bottom.nix
    ./common.nix
    ./direnv.nix
    ./extractors.nix
    ./fd.nix
    ./fzf.nix
    ./git.nix
    ./gnome.nix
    ./gtk.nix
    ./jj.nix
    ./monitoring.nix
    ./nix-your-shell.nix
    ./ripgrep.nix
    ./secret.nix
    ./spicetify.nix
    ./zellij.nix
    ./zoxide.nix
  ];
}
